{"name": "调试运算新功能", "status": "failed", "statusDetails": {"message": "AssertionError: 断言失败 -|- 实际结果:None || 预期结果: 成功", "trace": "cls = <class 'tools.data_process.DataProcess'>\nresponse = {'data': {'create_time': 1619624934, 'id': 516, 'role_id': -1, 'username': 'tery'}, 'meta': {'msg': '创建成功', 'status': 201}}\nexpect_str = '{\"$.msg\": \"成功\"}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        expect_str = rep_expr(expect_str, DataProcess.response_dict)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言',  f'实际结果:{actual} = 预期结果:{v}')\n            try:\n>               assert actual == v\nE               AssertionError\n\ntools\\data_process.py:118: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\ncases = ['case_017', '调试运算新功能', 'users/', '读', 'post', 'data', ...]\n\n    def test_main(cases):   # 不使用数据库功能\n        # 发送请求\n        response, expect, sql = BaseRequest.send_request(cases)\n        # 断言操作\n>       DataProcess.assert_result(response, expect)\n\ntest\\test_api.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'tools.data_process.DataProcess'>\nresponse = {'data': {'create_time': 1619624934, 'id': 516, 'role_id': -1, 'username': 'tery'}, 'meta': {'msg': '创建成功', 'status': 201}}\nexpect_str = '{\"$.msg\": \"成功\"}'\n\n    @classmethod\n    def assert_result(cls, response: dict, expect_str: str):\n        \"\"\" 预期结果实际结果断言方法\n        :param response: 实际响应结果\n        :param expect_str: 预期响应内容，从excel中读取\n        return None\n        \"\"\"\n        # 后置sql变量转换\n        expect_str = rep_expr(expect_str, DataProcess.response_dict)\n        expect_dict = convert_json(expect_str)\n        index = 0\n        for k, v in expect_dict.items():\n            # 获取需要断言的实际结果部分\n            actual = extractor(response, k)\n            index += 1\n            logger.info(f'第{index}个断言,实际结果:{actual} | 预期结果:{v} \\n断言结果 {actual == v}')\n            allure_step(f'第{index}个断言',  f'实际结果:{actual} = 预期结果:{v}')\n            try:\n                assert actual == v\n            except AssertionError:\n>               raise AssertionError(f'断言失败 -|- 实际结果:{actual} || 预期结果: {v}')\nE               AssertionError: 断言失败 -|- 实际结果:None || 预期结果: 成功\n\ntools\\data_process.py:120: AssertionError"}, "steps": [{"name": "请求地址", "status": "passed", "attachments": [{"name": "请求地址", "source": "51fb2384-14ca-48e0-af52-f2a0b576e1a3-attachment.txt", "type": "text/plain"}], "start": 1619624939242, "stop": 1619624939243}, {"name": "请求头", "status": "passed", "attachments": [{"name": "请求头", "source": "5f86109a-8db1-4bd0-b9e8-f75dfbf8d969-attachment.txt", "type": "text/plain"}], "start": 1619624939243, "stop": 1619624939245}, {"name": "请求参数", "status": "passed", "attachments": [{"name": "请求参数", "source": "dd96a9ff-14f4-47d8-8c69-189952e3ff65-attachment.txt", "type": "text/plain"}], "start": 1619624939245, "stop": 1619624939246}, {"name": "上传文件", "status": "passed", "attachments": [{"name": "上传文件", "source": "9d02af45-7a3f-4492-a712-f0c82046080c-attachment.txt", "type": "text/plain"}], "start": 1619624939246, "stop": 1619624939247}, {"name": "响应耗时(s)", "status": "passed", "attachments": [{"name": "响应耗时(s)", "source": "7dbdea7e-19dd-4150-bf18-7a7ff0313ff6-attachment.txt", "type": "text/plain"}], "start": 1619624939439, "stop": 1619624939440}, {"name": "响应内容", "status": "passed", "attachments": [{"name": "响应内容", "source": "266a6f35-1fa5-4662-a11b-48ac7c9ded77-attachment.txt", "type": "text/plain"}], "start": 1619624939440, "stop": 1619624939441}, {"name": "存储实际响应", "status": "passed", "attachments": [{"name": "存储实际响应", "source": "91747a5b-0797-4645-a3b9-e7754e910c67-attachment.txt", "type": "text/plain"}], "start": 1619624939441, "stop": 1619624939442}, {"name": "第1个断言", "status": "passed", "attachments": [{"name": "第1个断言", "source": "de288f89-128f-4194-b05f-45348d885fd6-attachment.txt", "type": "text/plain"}], "start": 1619624939443, "stop": 1619624939444}], "attachments": [{"name": "stderr", "source": "ff12222b-09f1-43d9-bd3b-aa38666270bc-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "cases", "value": "['case_017', '调试运算新功能', 'users/', '读', 'post', 'data', '', '{\"username\": \"tery\",\"password\": \"eval`1+2`\"}', '', '{\"$.msg\": \"成功\"}']"}], "start": 1619624939242, "stop": 1619624939445, "uuid": "a9f6769b-e53c-4324-b1d5-2d8fc512968a", "historyId": "2a3dfa6b36ee5ab01504c51319b8492e", "testCaseId": "881516e7ef2e2aa5436f6a3c3e6a5bcb", "fullName": "test.test_api#test_main", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "LYL"}, {"name": "thread", "value": "12004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api"}]}